#!/usr/bin/env node
var dust = require('../bin/dust');

// set up active mod from config file (default: c64)
dust.config.mod = require("../mods/" + dust.config.activeMod + '/config/mod.json');

// get texts used for this mod
require("../mods/" + dust.config.activeMod + '/lib/dust_text');

/* Initial Message */
dust.shell.exec("clear");

// show Dustlayer logo unless disabled by configuration
if (dust.config.dustLogo === true) {
    dust.text.dustLogo();
}
// show welcome message and version number
dust.text.welcomeMessage(dust.env.operatingSystem+ " " + dust.env.osVersion, dust.env.dustVersion);

// include modded tests
require("../mods/" + dust.config.activeMod + '/lib/dust_test');

// include modded setup
require("../mods/" + dust.config.activeMod + '/lib/dust_setup');

// include modded commands
require("../mods/" + dust.config.activeMod + '/lib/dust_cmd');

// include modded templates
require("../mods/" + dust.config.activeMod + '/lib/dust_templates');

dust.cmd.parse(process.argv);




